# Generated by Django 4.1 on 2022-09-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAutoSur', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citroen',
            old_name='nombre',
            new_name='version',
        ),
    ]
