# Generated by Django 4.1 on 2022-10-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAutoSur', '0003_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='citroen',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes_citroen'),
        ),
        migrations.AddField(
            model_name='fiat',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes_fiat'),
        ),
        migrations.AddField(
            model_name='peugeot',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes_peugeot'),
        ),
        migrations.AddField(
            model_name='renault',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes_renault'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(null=True, upload_to='avatares'),
        ),
    ]
