# Generated by Django 4.1 on 2022-10-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAutoSur', '0004_citroen_imagen_fiat_imagen_peugeot_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renault',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_renault'),
        ),
    ]
