# Generated by Django 4.1 on 2022-10-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAutoSur', '0005_alter_renault_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renault',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes_renault'),
        ),
    ]
